org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

minecraftVersion=26.1.2
modVersion=26.1.2-1.0.1
currentChangelog=- Doubled the amount of autocrafting pattern slots. It's also configurable in the config\n- Fixed a crash

refinedarchitectVersion=1.6.4
refinedstorageVersion=3.0.5
#refinedstorageMekanismIntegrationVersion=1.1.1
#mekanismVersion=1.21.1-10.7.17.83
#refinedTypesVersion=7213645
#arsNouveauVersion=5.10.3.1201
#industrialForegoingVersion=3.6.34
#industrialForegoingSoulsVersion=6235883
jadeVersionNeoForge=26.1.1
jadeVersionFabric=26.1.0